remote_theme: pmarsceill/just-the-docs
# Set a path/url to a logo that will be displayed instead of the title
logo: ""
# Enable support for hyphenated search words:
search_tokenizer_separator: /[\s/]+/
# Aux links for the upper right navigation
aux_links:
  "RustLabs on GitHub":
    - "https://github.com/sangam14/RustLabs/"
    
# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/sangam14/RustLabs/" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
    
